In [4]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

print(type(a))

<class 'list'>


In [3]:
a[0]

1

In [5]:
a[2:]

[3, 4, 5, 6, 7, 8, 9]

In [6]:
a[2:-2]

[3, 4, 5, 6, 7]

In [9]:
A = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]
print(A)
print(type(A))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
<class 'list'>


In [11]:
import numpy as np
A = np.array(A)

In [16]:
A[:, 2]

array([3, 8])

In [17]:
A[1, :]

array([ 6,  7,  8,  9, 10])

In [19]:
B = np.array([
    [4, 2, 5],
    [9, -1, 3],
    [2, 3, -1]
])

In [23]:
np.linalg.inv(B)

array([[-0.05594406,  0.11888112,  0.07692308],
       [ 0.1048951 , -0.0979021 ,  0.23076923],
       [ 0.2027972 , -0.05594406, -0.15384615]])

In [24]:
λ = 10

In [25]:
🍎 = 23.4

SyntaxError: invalid character '🍎' (U+1F34E) (3762144854.py, line 1)

In [27]:
내꺼 = 10

In [35]:
def 일해라(너):
    return 너 ** 2
너님 = 10
일해라(너님)

100

In [34]:
numbers = [1, 2, 3, 4, 5]
result = [x ** 2 for x in numbers]
print(result)

[1, 4, 9, 16, 25]
